### ISSUE TITLE
[enhancement requst] log enhancement in verbose mode

### ISSUE THREAD

**Issue by GreatMichaelLee** [damonto/estkme-cloud#4]
hi there:

Recently I setup a server on my private server and using different listen port from default.It is great. However, I found there were occasianlly some new connections outside which is not issuing by myself, so I would like to trace those connectionscome from where, is there any possible that you can add some tracing records that to show the connection source IP address in the debug log under the verbose mode? currently there is only the connection id(which I don't know what it is but I guess it is randomly generated internally right?) 

and addtionally, is there any persistent log file(or any way generate that?) ,for now I can only check out those logs for recent several rows by issuing 'systemctl status estkme-cloud', and the earlier logs I cannot stat. 

thanks!

![image](https://github.com/user-attachments/assets/5e10c8b9-ecc0-47ac-aeee-bbce3fdc3dc4)

**Comment by damonto** [comment]
A security team or hackers may scan your network to detect which ports are open. If you send your server address to social media apps such as WeChat, Telegram, Line, etc., they may try to establish a connection to preview the content.

**Comment by GreatMichaelLee** [comment]
Yes I understand.I never published the address and port,so is that possible to enhance the log? I don’t like use the system firewall to track (e.g ufw) as it is not friendly and if it is doable I will appreciate.thanks
